name: Is up to date?

on: [push]

jobs:
  check:
    name: Check ImageApprovals
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout demos
        uses: actions/checkout@v2
        with:
          path: demos   

      - name: Checkout ImageApprovals
        uses: actions/checkout@v2
        with:
          repository: p-podsiadly/ImageApprovals
          path: upstream

      - name: Check ImageApprovals.hpp
        run: |
          diff demos/dependencies/ImageApprovals/ImageApprovals.hpp upstream/single_header/ImageApprovals.hpp
